version: 0.0
os: linux
files:
  # lasci . perchè devi caricare tutta l'applicazione
  - source: .
  # var/www/html 
    destination: /home/ubuntu
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: pipeline_scripts/ApplicationStart.sh
      runas: ubuntu